### ISSUE TITLE
Duplicate _session.mount(...) in _get_requests_session function

### ISSUE THREAD

**Issue by anhtt-dsoft** [miguelgrinberg/microflack_common#2]
Hi Mr. Miguel Grinberg,

Thank you so much for the microflack sample code. I have followed your presentation at PyCon and learn a lot from it. I just have one question, that is there are two same line of mounting the _session at https://github.com/miguelgrinberg/microflack_common/blob/master/microflack_common/requests.py#L25. I just wonder whether it is just a typo mistake or something else. Thanks.

**Comment by miguelgrinberg** [comment]
The two lines configure https:// and http:// URLs, which can have different retry settings.

**Comment by anhtt-dsoft** [comment]
It's clear now. Thanks.
